services:
  db:
    image: postgres:15
    container_name: dw_postgres
    restart: always
    environment:
      POSTGRES_USER: dw
      POSTGRES_PASSWORD: dwpass
      POSTGRES_DB: dwdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
